#include <conio.h.>
#include <iostream.h>

void main ()
{
clrscr();
cout <<"aaaaaaaaaa    yyyy     yyyy    uuuu    uuuu"<<endl;
cout <<"aaaaaaaaaa    yyyy     yyyy    uuuu    uuuu"<<endl;
cout <<"aa      aa     yyy    yyyy     uuuu    uuuu"<<endl;
cout <<"aa      aa      yyy  yyyy      uuuu    uuuu"<<endl;
cout <<"aaaaaaaaaa       yyyyyyy       uuuu    uuuu"<<endl;
cout <<"aa      aa        yyyy         uuuu    uuuu"<<endl;
cout <<"aa      aa        yyyy         uuuu    uuuu"<<endl;
cout <<"aa      aa        yyyy         uuuu    uuuu"<<endl;
cout <<"aa      aa        yyyy         uuuuuuuuuuuu"<<endl;
cout <<"aa      aa        yyyy         uuuuuuuuuuuu"<<endl;

getch();
}
